### ISSUE TITLE
Wirft javascript exeptions

### ISSUE THREAD

**Issue by lukas-h** [HoverBaum/BlankUp-Electron#4]
![exception](https://cloud.githubusercontent.com/assets/10634693/18029055/c7c90dac-6c8d-11e6-8bf1-d6705dc45c84.png)
Das passiert bei mir, wenn man `CTRL-R` drückt, bzw. das Programm reloaden möchte. Außerdem passiert es bei dem Menüeintrag `Help -> Learn More`. Bei jeder der Fehlermeldungen wird jeweils eine andere Zeile im JS angezeigt.

**Comment by HoverBaum** [comment]
Danke fürs reporten, die sind mir wohl beim manuellen Testen durch die Lappen gegangen.

Sollte nicht schwer zu fixen sein. Werde hoffentlich in der kommenden Woche ein release mit dem Patch für diesen Bug veröffentlichen können.

**Comment by HoverBaum** [comment]
The fix for this is now published in release v1.1.0
